name: Check profiles

on: 
  pull_request:
    branches: 
      - main 
    paths:
      - 'profiles/**'
      - '.github/workflows/check_profiles.yml'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  check_profiles:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download validator
        run: |
          curl -LJO https://github.com/SoftFever/Orca_tools/releases/download/1/OrcaSlicer_profile_validator
          chmod +x ./OrcaSlicer_profile_validator

      - name: Run validation for each profile version
        run: |
          for dir in ./profiles/*/
          do
            echo "Validating profiles in $dir"
            python3 ./scripts/orca_extra_profile_check.py --dir "$dir"
            ./OrcaSlicer_profile_validator -p "$dir" -l 2
          done
